### ISSUE TITLE
Performance DLC

### ISSUE THREAD

**Issue by Br0k30n3** [YolospaceHacker/YoloIssues#10]
![image](https://user-images.githubusercontent.com/18095714/144137292-a2d5b4ba-e90c-41ae-a9e0-01f9d5a519f9.png)

upgraded my windows to be able to enable hyper v, enabled virtualization. getting this error when loading up

**Comment by Br0k30n3** [comment]
OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-CAULRNM
System Manufacturer	System manufacturer
System Model	System Product Name
System Type	x64-based PC
System SKU	SKU
Processor	Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, 4008 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 3802, 3/15/2018
SMBIOS Version	3.0
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	MAXIMUS VIII HERO
BaseBoard Version	Rev 1.xx
Platform Role	Desktop
Secure Boot State	Off
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume3
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.1151"

Time Zone	Eastern Standard Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.9 GB
Available Physical Memory	21.3 GB
Total Virtual Memory	36.7 GB
Available Virtual Memory	22.6 GB

**Comment by jossets** [comment]
Please follow the Faq: 
https://yolospacehacker.com/en/help.php?virt

https://yolospacehacker.com/fr/help.php?virt

**Comment by jossets** [comment]
Having VirtualBox whith Hyper-V running is an experimental feature. (https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/hyperv-support.html)

It is usually better to choose HyperV or virtualbox.
You need to disable HyperV, or customize Virtualbox.

**Comment by Br0k30n3** [comment]
I understand that you closed this, I do want you to know that after this was summitted initially I did disable HyperV and I tried customizing the VM to give it more ram but when ever the game starts the customized VM gets wiped and the game starts a new one with default settings.

**Comment by jossets** [comment]
If you want to customize the VM, make a Clone of the VM, modify it as you which, then modify spacehacker.ini
```
[challserver]
hacklab=false
virtualbox=false
qemu=false
custom=challs_myvirtualbox

[challs_myvirtualbox]
mode=virtualbox
server=127.0.0.1
port=9022
login=yolo
password=yoloyolo
opt_challs=/opt/challs/
scen_path=scenario/
scen_file=scenario_00.txt
```

Start the VM before the game, and stop it manually.
