### ISSUE TITLE
Out of map on the spawn, can't restart new game ?

### ISSUE THREAD

**Issue by Thomysr** [YolospaceHacker/YoloIssues#11]
![image](https://user-images.githubusercontent.com/71434237/145867910-c878c3c5-ce74-4ec7-befe-54d8e710007e.png)

**Comment by jossets** [comment]
To come back, you must hack the teleport.

Or, you can use the Menu/Config/Game  - Reset Position button

![image](https://user-images.githubusercontent.com/13644560/145876071-1ee63839-1d8c-4c42-b87d-ac37a86ae684.png)
