### ISSUE TITLE
Clickable element through walls

### ISSUE THREAD

**Issue by caltera** [YolospaceHacker/YoloIssues#3]
Title :
Some element can be clicked through walls

Version of Yolo :
Steam BuildId = 7052867

Describe error with details :
The guard pc and workshop (atelier) pc are clickable through the wall without the need to crack the entrance first
Edit: post-it and id card too, console to get out of warehouse from the alley too

Can you reproduce this error each time ?
Yes, from the alley for the workshop, and from behind the guard cabin for the guard computer

Step by step, how to reproduce ?
Click on wall, the window for the computer appears. 

Join Yolo Log (without log, issue will be not analyzed and will be closed)
[yolospacehacker_2021_07_22__14_23_11.log](https://github.com/YolospaceHacker/YoloIssues/files/6862326/yolospacehacker_2021_07_22__14_23_11.log)

**Comment by jossets** [comment]
Fixed
