### ISSUE TITLE
Error with John The Ripper : Sorry, AVX2 is required for this build

### ISSUE THREAD

**Issue by neoxeo** [YolospaceHacker/YoloIssues#6]
Version of Yolo :
Steam BuildId = 7052867

Describe error with details :
When I try to launch john I have this message : 
yolo@yoloxterm:~$ john hash.txt
Sorry, AVX2 is required for this build

Can you reproduce this error each time ?
Yes with Qemu

Step by step, how to reproduce ?
Launch Xterm and type john

Join Yolo Log (without log, issue will be not analyzed and will be closed)
nothing is present in the log for this error
![CPU](https://user-images.githubusercontent.com/5283778/127775535-8f22f401-b990-4a46-9aec-4e417b62fd25.jpg)

**Comment by neoxeo** [comment]
On the same machine, on Windows with john 1.9.0, it works perfectly

Another thing : Qemu 6.0 is now stable, it will be a good thing to migrate to this version.

**Comment by jossets** [comment]
Recompiled john without AVX2  support
