### ISSUE TITLE
Mission Progress Lost

### ISSUE THREAD

**Issue by Br0k30n3** [YolospaceHacker/YoloIssues#9]
I completed all of the mission except for the Artefact ( I was on 10.10.14.15)  logged back in and all my progress on the missions is lost,  I think I kept the flags but it is having me go through the whole mission again.

**Comment by Br0k30n3** [comment]
it appears that all of the doors are unlocked, seems that they are just not checked off on the mission task list and the NPC's dialogue is going through the tutorial and introductions all over again

**Comment by jossets** [comment]
The progress file is located at: C:\Users\YOUWINDOWSUSERNAME\AppData\Roaming\YoloSpaceHacker\saves
The file is: save.dat 
If this file is corruped, you'll loose your progress.
To avoid this, each time a 'validated' save.dat is loaded, the game write a copy: save.dat.backup

Replace save.dat by save.dat.backup, you should recover you progress.
If not, join us on discord, I'll give you a validated file.

**Comment by Br0k30n3** [comment]
Thank you
